
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-analyzer-ml
  labels:
    app: cv-analyzer-ml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cv-analyzer-ml
  template:
    metadata:
      labels:
        app: cv-analyzer-ml
    spec:
      containers:
      - name: cv-analyzer-ml
        image: cv-analyzer-ml:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: CV_JD_MODEL_PATH
          value: "/app/models/cv_jd_matcher_best.pt"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cv-analyzer-ml-service
spec:
  selector:
    app: cv-analyzer-ml
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
